# Generated by Django 4.0.3 on 2022-04-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o título da demanda', max_length=100, verbose_name='Título da demanda')),
                ('data_entrega', models.DateField(verbose_name='Data de entrega')),
                ('status', models.CharField(max_length=100, verbose_name='Status da demanda')),
                ('is_urgente', models.BooleanField(verbose_name='É urgente?')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição da demanda')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('estado', models.CharField(choices=[('SP', 'São Paulo'), ('PR', 'Paraná')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do setor')),
                ('area_atuacao', models.CharField(max_length=100, verbose_name='Área de atuação')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Digite seu nome completo', max_length=50, verbose_name='Nome da pessoa')),
                ('nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o título da demanda', max_length=50, verbose_name='Título da demanda')),
                ('data_inicial', models.DateField(verbose_name='Data de início')),
                ('data_final', models.DateField(verbose_name='Data final')),
                ('og', models.CharField(max_length=3, verbose_name='Ordem de grandeza')),
                ('lista_de_atividades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.atividade')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.setor'),
        ),
    ]
